AWSTemplateFormatVersion: 2010-09-09
Parameters:
  AWSAccountId:
    Type: String
    Description: AWS Account ID
  AWSECRAdminUser:
    Type: String
    Description: Admin User who can push ECR images
  AWSECRRepoName:
    Type: String
    Description: ECR Repository Name
  PrefixName:
    Type: String
    Description: Prefix for all of the resources

Resources:
  ProdRepository:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName: !Join ["-", [!Ref PrefixName, "repo"]]
    
Outputs:
  SimpleECRArn:
    Description: The ECR Repository ARN
    Value: !Join 
      - ''
      - - !GetAtt 
          - ProdRepository
          - Arn  