AWSTemplateFormatVersion: 2010-09-09
Parameters:
  AWSECRRepoName:
    Type: String
    Description: ECR Repository Name
  PrefixName:
    Type: String
    Description: Prefix for all of the resources

Resources:
  ProdRepository:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName: !Join ["-", [!Ref PrefixName, !Ref AWSECRRepoName]]
    
Outputs:
  PyAPIECRArn:
    Description: The ECR Repository ARN
    Value: !Join 
      - ''
      - - !GetAtt 
          - ProdRepository
          - Arn