name: prod-ecs

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies

      - name: Install dependencies
        run: pip install -r app/requirements.txt

      - name: Docker build and run
        run: |
          docker build -t kaokakelvin/py-api-ecr-repo:latest -t 636181284446.dkr.ecr.us-east-1.amazonaws.com/py-api-ecr-repo:latest .
          docker run -dit --name py-api-container -p 80:7000 kaokakelvin/py-api-ecr-repo:latest

      - name: Build ECR stack
        run: bash cloudformation/cfn-ecr-deploy.sh

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build ECS stack
        run: bash cloudformation/cfn-ecs-deploy.sh